### ISSUE TITLE
Crash on import of SBML model

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#704]
**Describe the bug**
I tried to load the [model](https://share.getcloudapp.com/nOu5gQBQ)  into the latest version that i downloaded from the website and the application died. 

**To Reproduce**
download the model and open

**Expected behavior**
What you expected to happen.

**Screenshots**

**Comment by lkeegan** [comment]
thanks @fbergmann !

stacktrace:

```
[W][model_species.cpp:  77] makeInitialConcentrationsValid :: Species 'Positionboolean' initialConcentration is not set:
[W][model_species.cpp:  91] makeInitialConcentrationsValid ::   - initialAmount also not set, using 0
[W][model_species.cpp:  77] makeInitialConcentrationsValid :: Species 'NPCA' initialConcentration is not set:
[W][model_species.cpp:  86] makeInitialConcentrationsValid ::   - using initialAmount / compartmentSize = 0 / 6563 = 0
[W][model_species.cpp:  77] makeInitialConcentrationsValid :: Species 'NPC' initialConcentration is not set:
[W][model_species.cpp:  86] makeInitialConcentrationsValid ::   - using initialAmount / compartmentSize = 380 / 6563 = 0.05790035044948956
[W][model_species.cpp:  77] makeInitialConcentrationsValid :: Species 'LaminA' initialConcentration is not set:
[W][model_species.cpp:  86] makeInitialConcentrationsValid ::   - using initialAmount / compartmentSize = 0 / 6563 = 0
[W][model_species.cpp:  77] makeInitialConcentrationsValid :: Species 'LaminAp' initialConcentration is not set:
[W][model_species.cpp:  86] makeInitialConcentrationsValid ::   - using initialAmount / compartmentSize = 204652 / 6563 = 31.18269084260247
AddressSanitizer:DEADLYSIGNAL
=================================================================
==372658==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x00000156c57e bp 0x7ffdb9e8e410 sp 0x7ffdb9e8e3e0 T0)
==372658==The signal is caused by a READ memory access.                                                                                                                                                                                                                                              
==372658==Hint: address points to the zero page.
    #0 0x156c57e in std::vector<QPoint, std::allocator<QPoint> >::size() const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:919:40
    #1 0x17099b8 in sme::geometry::Compartment::nPixels() const /home/liam/SSC/spatial-model-editor/src/core/model/inc/geometry.hpp:44:64
    #2 0x1ec5a39 in sme::geometry::Field::Field(sme::geometry::Compartment const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, unsigned int) /home/liam/SSC/spatial-model-editor/src/core/model/src/geometry.cpp:207:38
    #3 0x2087b95 in void __gnu_cxx::new_allocator<sme::geometry::Field>::construct<sme::geometry::Field, sme::geometry::Compartment const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, unsigned int&>(sme::geometry::Field*, sme::geometry::Compartment const*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, double&&, unsigned int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:150:23
    #4 0x2086edb in void std::allocator_traits<std::allocator<sme::geometry::Field> >::construct<sme::geometry::Field, sme::geometry::Compartment const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, unsigned int&>(std::allocator<sme::geometry::Field>&, sme::geometry::Field*, sme::geometry::Compartment const*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, double&&, unsigned int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:512:8
    #5 0x2087259 in void std::vector<sme::geometry::Field, std::allocator<sme::geometry::Field> >::_M_realloc_insert<sme::geometry::Compartment const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, unsigned int&>(__gnu_cxx::__normal_iterator<sme::geometry::Field*, std::vector<sme::geometry::Field, std::allocator<sme::geometry::Field> > >, sme::geometry::Compartment const*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, double&&, unsigned int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:449:4
    #6 0x2073b88 in sme::geometry::Field& std::vector<sme::geometry::Field, std::allocator<sme::geometry::Field> >::emplace_back<sme::geometry::Compartment const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, unsigned int&>(sme::geometry::Compartment const*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, double&&, unsigned int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:121:4
    #7 0x2070904 in sme::model::ModelSpecies::ModelSpecies(libsbml::Model*, sme::model::ModelCompartments const*, sme::model::ModelGeometry const*, sme::model::ModelParameters const*, sme::simulate::SimulationData*, sme::model::Settings*) /home/liam/SSC/spatial-model-editor/src/core/model/src/model_species.cpp:250:16
    #8 0x1ee0a11 in std::_MakeUniq<sme::model::ModelSpecies>::__single_object std::make_unique<sme::model::ModelSpecies, libsbml::Model*&, sme::model::ModelCompartments*, sme::model::ModelGeometry*, sme::model::ModelParameters*, sme::simulate::SimulationData*, sme::model::Settings*>(libsbml::Model*&, sme::model::ModelCompartments*&&, sme::model::ModelGeometry*&&, sme::model::ModelParameters*&&, sme::simulate::SimulationData*&&, sme::model::Settings*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:962:34
    #9 0x1edeae1 in sme::model::Model::initModelData(bool) /home/liam/SSC/spatial-model-editor/src/core/model/src/model.cpp:81:18
    #10 0x1ee20c5 in sme::model::Model::importFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/liam/SSC/spatial-model-editor/src/core/model/src/model.cpp:151:3
    #11 0x1474668 in MainWindow::MainWindow(QString const&, QWidget*) /home/liam/SSC/spatial-model-editor/src/gui/mainwindow.cpp:117:11
    #12 0x1468f5d in main /home/liam/SSC/spatial-model-editor/src/spatial-model-editor.cpp:33:14
    #13 0x7fb9bd344564 in __libc_start_main csu/../csu/libc-start.c:332:16
    #14 0x13b556d in _start (/home/liam/SSC/spatial-model-editor/build/src/spatial-model-editor+0x13b556d)
```

**Comment by lkeegan** [comment]
Closing as this now displays an error instead of crashing (and supporting species on membranes is already a long-standing open issue): 

<img width="795" height="189" alt="Image" src="https://github.com/user-attachments/assets/c7e05c23-44dc-4ab0-9864-55285de27650" />
